(* Back-edge proof: from pc+248 to pc+108 *)
e(X_GEN_TAC `i:num` THEN STRIP_TAC THEN
  FIRST_X_ASSUM(MP_TAC o SPEC `i:num`) THEN
  ANTS_TAC THENL [ASM_ARITH_TAC; STRIP_TAC] THEN
  CONV_TAC(RATOR_CONV(LAND_CONV(TOP_DEPTH_CONV let_CONV))) THEN
  ENSURES_INIT_TAC "s0" THEN
  SUBGOAL_THEN
   `8 <= val(word_sub (buflen:int64) (word(8 * i)))`
  ASSUME_TAC THENL
   [REWRITE_TAC[VAL_WORD_SUB_CASES; VAL_WORD; DIMINDEX_64] THEN
    CONV_TAC(DEPTH_CONV NUM_MOD_CONV) THEN COND_CASES_TAC THENL
     [UNDISCH_TAC `~(val(buflen:int64) < 8 * (i + 1))` THEN
      POP_ASSUM MP_TAC THEN ARITH_TAC;
      UNDISCH_TAC `~(val(buflen:int64) < 8 * (i + 1))` THEN
      POP_ASSUM MP_TAC THEN ARITH_TAC];
    ALL_TAC] THEN
  ARM_STEPS_TAC MLDSA_REJ_UNIFORM_ETA4_EXEC (1--2) THEN
  ENSURES_FINAL_STATE_TAC THEN ASM_REWRITE_TAC[]);;
