(* Exit: debug - check what VAL_WORD_SUB_CASES produces *)
e(CONV_TAC(TOP_DEPTH_CONV let_CONV) THEN
  VAL_INT64_TAC
   `LENGTH (SCRATCH_ETA4 (SUB_LIST (0,8 * N) (inbytes:byte list)))` THEN
  SUBGOAL_THEN `8 * N <= val(buflen:int64)` ASSUME_TAC THENL
   [ASM_CASES_TAC `N = 0` THEN ASM_REWRITE_TAC[MULT_CLAUSES; LE_0] THEN
    FIRST_X_ASSUM(MP_TAC o SPEC `N - 1`) THEN
    ASM_REWRITE_TAC[ARITH_RULE `n - 1 < n <=> ~(n = 0)`] THEN
    ARITH_TAC;
    ALL_TAC] THEN
  SUBGOAL_THEN `val(word(8 * N):int64) = 8 * N` ASSUME_TAC THENL
   [REWRITE_TAC[VAL_WORD; DIMINDEX_64] THEN MATCH_MP_TAC MOD_LT THEN
    TRANS_TAC LTE_TRANS `val(buflen:int64)` THEN
    ASM_REWRITE_TAC[VAL_BOUND_64];
    ALL_TAC]);;
