(* Second half: P' at pc+256 -> Q at pc+340 *)
(* Structure: CMP/CSEL clamp, MOV/MOV init, 16-iter copy loop, MOV/ADD *)

e(REWRITE_TAC[MAYCHANGE_REGS_AND_FLAGS_PERMITTED_BY_ABI] THEN
  CONV_TAC(TOP_DEPTH_CONV let_CONV) THEN
  (* Establish outlen < 272 *)
  SUBGOAL_THEN
   `LENGTH (SCRATCH_ETA4 (SUB_LIST (0,8 * N) inbytes)) < 272`
  ASSUME_TAC THENL
   [ASM_CASES_TAC `N = 0` THENL
     [ASM_REWRITE_TAC[MULT_CLAUSES; SUB_LIST_CLAUSES; SCRATCH_ETA4_EMPTY] THEN
      REWRITE_TAC[LENGTH] THEN CONV_TAC NUM_REDUCE_CONV;
      FIRST_X_ASSUM(MP_TAC o SPEC `N - 1`)] THEN
    ASM_REWRITE_TAC[ARITH_RULE `n - 1 < n <=> ~(n = 0)`] THEN
    MATCH_MP_TAC(ARITH_RULE
     `l' <= l + 16 ==> ~(b < x) /\ l < 256 ==> l' < 272`) THEN
    MP_TAC(ISPECL [`inbytes:byte list`; `8 * (N - 1)`; `8`; `0`]
        SUB_LIST_SPLIT) THEN
    ASM_SIMP_TAC[ARITH_RULE `~(N = 0) ==> 8 * (N - 1) + 8 = 8 * N`] THEN
    DISCH_THEN SUBST1_TAC THEN REWRITE_TAC[SCRATCH_ETA4_APPEND] THEN
    REWRITE_TAC[LENGTH_APPEND; LE_ADD_LCANCEL; ADD_CLAUSES] THEN
    REWRITE_TAC[LENGTH_SCRATCH_ETA4] THEN
    W(MP_TAC o PART_MATCH lhand LENGTH_FILTER o lhand o snd) THEN
    MATCH_MP_TAC(REWRITE_RULE[IMP_CONJ_ALT] LE_TRANS) THEN
    REWRITE_TAC[LENGTH_NIBBLES; LENGTH_SUB_LIST] THEN ARITH_TAC;
    ALL_TAC] THEN
  VAL_INT64_TAC
   `LENGTH (SCRATCH_ETA4 (SUB_LIST (0,8 * N) (inbytes:byte list)))` THEN
  ABBREV_TAC
   `outlen = LENGTH(SCRATCH_ETA4 (SUB_LIST (0,8 * N) (inbytes:byte list)))` THEN
  (* Case split on whether outlen >= 256 *)
  ASM_CASES_TAC `256 <= outlen` THEN
  ENSURES_INIT_TAC "s0" THEN
  ARM_STEPS_TAC MLDSA_REJ_UNIFORM_ETA4_EXEC (1--4));;
